server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires "0";
        add_header Content-Type "text/html; charset=utf-8";

        # Отключение ETag
        etag off;
        try_files $uri $uri/ =404;
    }
    
    location /api/ {
        proxy_pass http://backend:8000;
    }

    location /docs {
        proxy_pass http://backend:8000;
    }

    location /openapi.json {
        proxy_pass http://backend:8000;
    }
}
