"""Добавили title сделки

Revision ID: 3452a6e6b270
Revises: 6474de3c08a3
Create Date: 2026-03-05 20:26:04.857164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3452a6e6b270'
down_revision: Union[str, Sequence[str], None] = '6474de3c08a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('title', sa.String(), nullable=True))
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    op.create_index(op.f('ix_deals_title'), 'deals', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deals_title'), table_name='deals')
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_column('deals', 'title')
    # ### end Alembic commands ###
