"""обновили сделки

Revision ID: 6474de3c08a3
Revises: d5cf96b044a8
Create Date: 2026-03-05 20:15:53.989218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '6474de3c08a3'
down_revision: Union[str, Sequence[str], None] = 'd5cf96b044a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ENUM('NEW', 'NEGOTIATION', 'WON', 'LOST', name='dealstatus').create(op.get_bind())
    op.add_column('deals', sa.Column('amount', sa.Numeric(), nullable=False))
    op.add_column('deals', sa.Column('status', sa.Enum('NEW', 'NEGOTIATION', 'WON', 'LOST', name='dealstatus'), nullable=False))
    op.add_column('deals', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('deals', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('deals', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'closed_at')
    op.drop_column('deals', 'updated_at')
    op.drop_column('deals', 'created_at')
    op.drop_column('deals', 'status')
    op.drop_column('deals', 'amount')
    # ### end Alembic commands ###
